version: '3.8'

volumes:
  build:
  deps:
  mysql:


x-service-defaults: &service-defaults
  build:
    context: .
    dockerfile: Dockerfile-dev
  ports:
    - '4000:4000'
  depends_on:
    - db
  volumes:
    - .:/opt
    - 'build:/opt/_build'
    - 'deps:/opt/deps'

services:
  web:
    <<: *service-defaults
    environment:
      - PHX_SERVER=true
      - MIX_ENV=dev
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=arvore_challenge
      - TIMEZONE=America/Sao_Paulo

  test:
    <<: *service-defaults
    command: mix do deps.get --only, coveralls --trace --color
    environment:
      - MIX_ENV=test
      - MYSQL_HOST=db
      - MYSQL_DATABASE=arvore_challenge_test
      - TIMEZONE=America/Sao_Paulo

  ci-test:
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: mix do deps.get --only, coveralls --trace --color
    depends_on:
      db:
        condition: service_healthy
    environment:
      - MIX_ENV=test
      - MYSQL_HOST=db
      - MYSQL_DATABASE=arvore_challenge_ci_test
      - TIMEZONE=America/Sao_Paulo
    ports:
      - '4008:4008'
    volumes:
      - .:/opt

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    ports:
      - '3306:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
