apiVersion: v1
kind: Service
metadata:
  name: arvore-challenge
  namespace: {{ .Release.Namespace }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  selector:
    app: arvore-challenge
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 4000
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: {{ .Release.Namespace }}
spec:
  externalName: arvorechallengeinstance.credrkngzkya.sa-east-1.rds.amazonaws.com
  selector:
    app: mysql-service
  type: ExternalName
status:
  loadBalancer: {}
