version: v1.0
name: Deploy to Fly.io
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804

blocks:
  - name: Deploy
    task:
      secrets:
        - name: Fly.io
      jobs:
      - name: Deploy
        commands:
          - checkout
          - curl -L https://fly.io/install.sh | bash
          - flyctl deploy --remote-only --access-token $FLY_API_TOKEN
