version: v1.0
name: Deploy to EKS
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804

blocks:
  - name: Deploy
    task:
      secrets:
        - name: AWS
        - name: AWS-k8
      jobs:
      - name: Deploy
        commands:
          - checkout
          - export ECR_PASSWORD=$(aws ecr get-login --no-include-email | awk '{print $6}')
          - kubectl delete secret aws-ecr || true
          - kubectl create secret docker-registry aws-ecr --docker-server="https://$ECR_REGISTRY" --docker-username=AWS --docker-password="$ECR_PASSWORD"
          - curl -L https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
          - helm upgrade arvore-challenge ./chart -n arvore-challenge --reuse-values --set env.image_hash=${SEMAPHORE_GIT_SHA}
  - name: Docker tag latest
    task:
      secrets:
        - name: AWS
      jobs:
        - name: ECR dacker push latest
          commands:
            - checkout
            - aws ecr get-login --no-include-email | bash
            - docker pull "${ECR_REGISTRY}:$SEMAPHORE_WORKFLOW_ID"
            - docker tag "${ECR_REGISTRY}:$SEMAPHORE_WORKFLOW_ID" "${ECR_REGISTRY}:latest"
            - docker push "${ECR_REGISTRY}:latest"